/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "ap-northeast-1",
  aws_cognito_region: "ap-northeast-1",
  aws_user_pools_id: "ap-northeast-1_mYlONVf7T",
  aws_user_pools_web_client_id: "6s3luch07i2sc2efmvj6jmjiva",
  oauth: {
    domain: "kampaicocktails-dev.auth.ap-northeast-1.amazoncognito.com",
    scope: [
      "phone",
      "email",
      "openid",
      "profile",
      "aws.cognito.signin.user.admin",
    ],
    redirectSignIn: "https://kampai-cocktails.herokuapp.com/",
    redirectSignOut: "https://kampai-cocktails.herokuapp.com/",
    responseType: "token",
  },
  federationTarget: "COGNITO_USER_POOLS",
};

export default awsmobile;
